# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=150)),
                ('venue_category', models.CharField(max_length=200)),
                ('venue_picture_url', models.CharField(max_length=250)),
                ('avg_rating', models.PositiveSmallIntegerField()),
                ('yelp_page_url', models.CharField(max_length=250)),
                ('votes', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('voters', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
