# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='price_range',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
