# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creator_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='voters',
            field=models.CharField(max_length=200),
        ),
    ]
