# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 22:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180127_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='all_voters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=None),
        ),
    ]
