# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_all_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='price_range',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
