# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180128_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='rating_is_integer',
            field=models.BooleanField(default=True),
        ),
    ]
