# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180206_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='all_voters',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='voters',
        ),
        migrations.AddField(
            model_name='choice',
            name='voters',
            field=models.ManyToManyField(to='polls.Voter'),
        ),
    ]
