# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_choice_num_voters'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('question', 'venue_name')]),
        ),
    ]
